[package]
name = "yttrium-bot"
version = "0.1.0"
authors = ["adamski234 <adamski234@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

yttrium = { git = "https://github.com/adamski234/yttrium" }
serenity = { version = "0.9", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
futures = "0.3"
serde = "1"
json5 = "0.3"